version: '3.8'

services:
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: dental_php
    working_dir: /var/www/html
    user: www-data
    volumes:
      - ./src/:/var/www/html
      - .docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - redis
    networks:
      - db-network
      - redis-network
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: dental_nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html
    networks:
      - db-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=qwAJnhsYgTXkWeSNpdvFzb
    networks:
      - db-network
  db:
    image: mysql:8
    restart: always
    container_name: dental_mysql
    environment:
      MYSQL_DATABASE: dental_data
      MYSQL_USER: dental_user
      MYSQL_PASSWORD: puKqCnhGVkNsmzEWaQJcxH
      MYSQL_ROOT_PASSWORD: qwAJnhsYgTXkWeSNpdvFzb
    ports:
      - "3307:3306"
    volumes:
      - .docker/data/db:/var/lib/mysql
    networks:
      - db-network
  redis:
    image: redis:alpine
    container_name: dental_redis
    volumes:
      - .docker/data/redis:/data
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
        - .env
    networks:
      - redis-network
networks:
  db-network:
    driver: bridge
  redis-network:
    driver: bridge
